import turtle
my_turtle = turtle.Turtle()
screen=turtle.Screen()
screen.bgcolor("gold")
pen=turtle.Turtle()
pen.fillcolor("silver")
pen.begin_fill()
my_turtle.forward(100)
my_turtle.right(90)
my_turtle.forward(100)
my_turtle.right(90)
my_turtle.forward(100)
my_turtle.right(90)
my_turtle.forward(100)
my_turtle.right(90)
